# Generated by Django 3.1.3 on 2020-11-20 18:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('wyvern', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='date_created',
            field=models.DateTimeField(verbose_name=datetime.datetime(2020, 11, 20, 18, 20, 21, 294471, tzinfo=utc)),
        ),
    ]
