# Generated by Django 3.1.1 on 2020-11-07 11:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('wyvern', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='date_created',
            field=models.DateTimeField(verbose_name=datetime.datetime(2020, 11, 7, 11, 33, 17, 94412, tzinfo=utc)),
        ),
    ]
