# Generated by Django 3.1.1 on 2020-09-10 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wyvern', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='people',
            old_name='role',
            new_name='status',
        ),
    ]
