# Generated by Django 3.1.3 on 2020-11-07 11:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('wyvern', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='date_created',
            field=models.DateTimeField(verbose_name=datetime.datetime(2020, 11, 7, 11, 53, 52, 816489, tzinfo=utc)),
        ),
        migrations.DeleteModel(
            name='Wyvern',
        ),
    ]
