# Generated by Django 3.1.3 on 2020-11-07 17:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('wyvern', '0002_auto_20201107_0853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='date_created',
            field=models.DateTimeField(verbose_name=datetime.datetime(2020, 11, 7, 17, 57, 9, 127455, tzinfo=utc)),
        ),
    ]
