# Generated by Django 3.1.3 on 2020-11-08 18:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('wyvern', '0003_auto_20201108_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='date_created',
            field=models.DateTimeField(verbose_name=datetime.datetime(2020, 11, 8, 18, 26, 37, 37311, tzinfo=utc)),
        ),
    ]
