# Generated by Django 3.1.3 on 2020-11-07 18:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('wyvern', '0004_auto_20201107_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='date_created',
            field=models.DateTimeField(verbose_name=datetime.datetime(2020, 11, 7, 18, 45, 21, 443792, tzinfo=utc)),
        ),
    ]
