# Generated by Django 3.1.3 on 2020-11-07 23:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('wyvern', '0005_auto_20201107_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='date_created',
            field=models.DateTimeField(verbose_name=datetime.datetime(2020, 11, 7, 23, 46, 18, 829821, tzinfo=utc)),
        ),
    ]
