# Generated by Django 3.1.3 on 2020-11-08 01:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('wyvern', '0007_auto_20201107_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='date_created',
            field=models.DateTimeField(verbose_name=datetime.datetime(2020, 11, 8, 1, 37, 12, 632060, tzinfo=utc)),
        ),
    ]
